### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Tauqeer20** [signetlabdei/quic-ns-3#23]
I clone quic repository and copy quic application and then when I try to build the file they show me error as shown in the attachment
![qui](https://user-images.githubusercontent.com/110641797/197353884-47f4e542-7e33-4071-a7ee-375441bc31ea.PNG)
 file.

**Comment by inayatalikhan** [comment]
I have a similar problem.

**Comment by Tauqeer20** [comment]
Anyone who can guide me about this error please..???

**Comment by inayatalikhan** [comment]
Tauqeer,

It simply says that the header file ns3/quic-socket.h does not exist. To solve this just copy this header file from ns-3-dev/src/quic/model directory to ns-3-dev/build/ns3. You may have the same error for a few other header files too. Copy them also and configure ns3 again.

**Comment by Tauqeer20** [comment]
I have to copy that file in build/ns3 only…??

**Comment by inayatalikhan** [comment]
not "only" just follow the steps in the readme file. My above comments are to solve the error.

**Comment by Tauqeer20** [comment]
Done. This error is solved thanks alot.! I follow the readme file steps but
they show error while build the file.!
Now when i run a quic-tester file they dont run alot they also show
error..! Any idea about this?

**Comment by Tauqeer20** [comment]
When I run an example of a quic file they show me the error "quic-module.h"
not found. The error message is attached in this email. Please if you have
any idea please let me know.

Thank you

**Comment by fedech** [comment]
The current version on the repo is updated to ns-3 version 3.31, and compatibility is not guaranteed for later versions. As the build system for ns-3 has changed, adding quic-socket.h and the other header files to the wscript no longer includes them in the build. An update to the current version is in progress, in the meantime the options for users are:
1) Use ns-3.31 or another ns-3 version still using the wscript-based build tool
2) Patch the build to include the QUIC header files

Closing this issue until the new version is released
