### ISSUE TITLE
Integration in ns3 filr

### ISSUE THREAD

**Issue by Tauqeer20** [signetlabdei/quic-ns-3#26]
I want to integrate Quic in ns3 project. So anyone can help me that how can I integrate Quic in the another ns3 file. The ns3 project link is given below where I want to integrate this. Please anyone have any knowledge about that please help me out. The link is as ; https://github.com/hansomesong/ns3-lisp.

Hoping for positive response.
Thanx

**Comment by fedech** [comment]
The issue tool is not the right place for help questions on the module.
