### ISSUE TITLE
Using multiple quic streams

### ISSUE THREAD

**Issue by Zohanoo67** [signetlabdei/quic-ns-3#29]
Hi,
How can we change the number of Quic streams to use? 
In quic-client.cc there is NumStreams attribute but it takes only 1 or 2 values not more than that. Also, I am not using QuicClient Class. I am using onoff application with Quic socket.

Does quic maintain a separate buffer for each stream?

**Comment by fedech** [comment]
The issue tracker is **not** a basic tutorial function, it should be used to report bugs in the module. 

The Send(packet, flags) method in QuicSocketBase manages stream creation automatically, just by putting the stream number in the flags parameter. This is clearly written in the QuicSocketBase documentation, and implemented in the src/applications/quic-client.cc file. For more details on the buffer management, we refer you to the paper in the readme.
