### ISSUE TITLE
Quic does not works in Wireless environment

### ISSUE THREAD

**Issue by Zohanoo67** [signetlabdei/quic-ns-3#30]
Although I have not received any response from the developer of the QUIC model for my previous queries. I have no choice but to ask here again.

The quick model is not working in a WiFi environment. I have a wifi client that sends quic traffic to a wired server but none of the packets are received and finally, the simulation ends with the error msg= sending in statIDLE.

Any help?

**Comment by fedech** [comment]
As for the other issue, this is not a help forum, but a bug tracking tool. Can you provide a minimal working example of your code, and a stack trace with the error you receive?

**Comment by Zohanoo67** [comment]
The problem has been solved after changing the ns3 version to the latest release. Thank you
