### ISSUE TITLE
Quic build Error

### ISSUE THREAD

**Issue by Tauqeer20** [signetlabdei/quic-ns-3#35]
../src/applications/model/quic-echo-client.cc:34:10: fatal error: ns3/quic-header.h: No such file or directory
 #include "ns3/quic-header.h"
compilation terminated.

This message shows while building the ns3 file. I am using ns3.32 on Ubuntu 18 and I copy the Quic file in the ns3.32 and also edit the application/wscript.
But when I build the ns3 after making the changes then this error shows..

Anyone knows about this error solution?

**Comment by fedech** [comment]
This tool is not meant as a help forum for debugging but as a bug tracker for the repository, please stop opening issues to ask basic questions
