### ISSUE TITLE
use tap bridge to send data packets from Docker quic-go to NS3 quic

### ISSUE THREAD

**Issue by MikeLee9527** [signetlabdei/quic-ns-3#37]
I want to use tap bridge to send data packets from Docker quic-go to NS3 quic, but when I start quic-go to send data packets, the first packet arrives at NS3 and an error message "no handler for socket" is displayed from quic-l4 protocol. cc line 569

**Comment by MikeLee9527** [comment]
`#include <iostream>
#include <fstream>

#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/internet-module.h"
#include "ns3/csma-module.h"
#include "ns3/applications-module.h"
#include "ns3/ipv4-global-routing-helper.h"
#include "ns3/tap-bridge-module.h"
#include "ns3/internet-apps-module.h"
#include "ns3/netanim-module.h"
#include <ns3/packet.h>
#include "ns3/quic-module.h"
#include "ns3/config-store-module.h"

using namespace ns3;



int 
main (int argc, char *argv[])
{
  Packet::EnablePrinting ();
  //std::string protocol = "udp";
  std::string mode = "UseBridge";    
  std::string tapName ="tap-test1";   

  CommandLine cmd;
  //cmd.AddValue ("protocol", "Protocol to use: tcp or udp", protocol);
  cmd.AddValue ("mode", "Mode setting of TapBridge", mode);
  cmd.AddValue ("tapName", "Name of the OS tap device", tapName);
  cmd.Parse (argc, argv);

  GlobalValue::Bind ("SimulatorImplementationType", StringValue ("ns3::RealtimeSimulatorImpl"));
  GlobalValue::Bind ("ChecksumEnabled", BooleanValue (true));

  NodeContainer nodesLeft;
  nodesLeft.Create (2);

  CsmaHelper csmaSN0;
  csmaSN0.SetChannelAttribute ("DataRate", StringValue ("100Mbps"));
  csmaSN0.SetChannelAttribute ("Delay", TimeValue (NanoSeconds (6560)));
  NetDeviceContainer devicesLeft = csmaSN0.Install (nodesLeft);

  NodeContainer nodes;
  nodes.Add(nodesLeft.Get(1));
  nodes.Create(1);

  Ptr<UniformRandomVariable> uv = CreateObject<UniformRandomVariable> ();
  uv->SetStream (50);
  RateErrorModel error_model;
  error_model.SetRandomVariable (uv);
  error_model.SetUnit (RateErrorModel::ERROR_UNIT_PACKET);
  error_model.SetRate (0.05);

  PointToPointHelper p2p;
  p2p.SetDeviceAttribute ("DataRate", StringValue ("512kbps"));
  p2p.SetChannelAttribute ("Delay", StringValue ("10ms"));
  p2p.SetDeviceAttribute ("ReceiveErrorModel", PointerValue (&error_model));
  NetDeviceContainer devices = p2p.Install (nodes);

    QuicHelper stack;
    stack.InstallQuic (nodes);
    stack.InstallQuic (nodesLeft.Get(0));

  /*InternetStackHelper internet;
  internet.Install (nodesLeft.Get(0));
  internet.Install (nodes);*/

  Ipv4AddressHelper ipv4;
  ipv4.SetBase ("10.1.1.0", "255.255.255.0");
  Ipv4InterfaceContainer interfacesLeft = ipv4.Assign (devicesLeft);

  ipv4.SetBase ("10.1.2.0", "255.255.255.0");
  Ipv4InterfaceContainer interfaces = ipv4.Assign (devices);

  TapBridgeHelper tapBridge (interfacesLeft.GetAddress (0));
  tapBridge.SetAttribute ("Mode", StringValue (mode));
  tapBridge.SetAttribute ("DeviceName", StringValue (tapName));
  tapBridge.Install (nodesLeft.Get (0), devicesLeft.Get (0));

  int serverPort = 2399; 
  
  QuicServerHelper server (serverPort);
  ApplicationContainer serverApps = server.Install (nodes.Get (1));
  serverApps.Start (Seconds (1.0));
  serverApps.Stop (Seconds (1200.0));


  Ipv4GlobalRoutingHelper::PopulateRoutingTables ();

  p2p.EnablePcapAll("p2p");

  // Trace routing tables 
  Ipv4GlobalRoutingHelper g;
  Ptr<OutputStreamWrapper> routingStream = Create<OutputStreamWrapper> ("dynamic-global-routing.routes", std::ios::out);
  g.PrintRoutingTableAllAt (Seconds (30), routingStream);
 
  Simulator::Stop (Seconds (305.));
  Simulator::Run ();
  Simulator::Destroy ();

}`



`package main

import (
    "context"
	"crypto/rand"
	"encoding/binary"
	"log"
    "crypto/tls"
    "time"
    "github.com/quic-go/quic-go"

)

func main() {
	// Set up a QUIC configuration
	quicConf := &quic.Config{}

	// Dial to the server
	sess, err := quic.DialAddr("10.1.2.2:2399", &tls.Config{}, quicConf)
	if err != nil {
		log.Fatal(err)
	}
	defer sess.CloseWithError(0, "")

	// Open a stream
	stream, err := sess.OpenStreamSync(context.Background())
	if err != nil {
		log.Fatal(err)
	}
	defer stream.Close()

	// Send data
	for {
		// Generate a random payload
		payload := make([]byte, 1024)
		rand.Read(payload)

		// Send the payload
		err := binary.Write(stream, binary.LittleEndian, payload)
		if err != nil {
			log.Fatal(err)
		}

		// Sleep for 1 second
		time.Sleep(1 * time.Second)
	}
}`

**Comment by fedech** [comment]
Hi,

The QUIC module was not built to support the full standard, only basic
functionalities, and while the packet format follows the standard,
encryption is not supported in the ns-3 module: as such, integrating
directly with real QUIC modules is unsupported. The error seems to be in
the TLS layer, which is exactly what is missing from ns-3-quic.

Federico
