### ISSUE TITLE
quic-variants-comparison and tcp-variants-comparison

### ISSUE THREAD

**Issue by miguelsp99** [signetlabdei/quic-ns-3#40]
Good afternoon,

I have been reading your paper "[Extending the ns-3 QUIC Module](https://dl.acm.org/doi/pdf/10.1145/3416010.3423224)" as I am doing a project in which I want to replicate the results obtained in that paper.

I have noticed that in section 3.2 Performance evaluation it is described that a dumbbell topology is being used, with a bottleneck link, but when reviewing both codes and comparing them I have observed that in the quic-variants-comparison example this topology is indeed used, but in the tcp-variants-comparison example there is no such bottleneck link.

The quic-variants-comparison file shows that the "sources" nodes correspond to the sender nodes, which connect to the "gateways" node via the "AccessLink" link. On the other hand, the "sinks" nodes correspond to the receiving nodes, which connect to the "gateways" node via the "LocalLink" link. And the two gateways nodes are connected to each other via the "Bottleneck" link, thus creating the dumbbell topology.

In the tcp-variants-comparison file, on the other hand, there is only one "gateways" node, and all the "sources" and "sinks" nodes are connected to it. The "sources" nodes via the "LocalLink" link, and the "sinks" via the "UnReLink" link (whose characteristics correspond to the "Bottleneck" link described in the case of quic).

**My question is: has this file been used for such simulations, or has any modification been made to it, or has a different file been used?**

In any case, could you please tell me which file has been used if any other file has been used. Or what modifications have been made to it if any?

I attach the pictures of the code described above:

On the left quic-variants-comparison, on the right tcp-variants-comparison:

![Captura](https://github.com/signetlabdei/quic-ns-3/assets/119290035/d1cb9503-586c-49cf-8707-f358d8a4ad01)
![Captura2](https://github.com/signetlabdei/quic-ns-3/assets/119290035/9c662b48-f8fc-4a71-9c5c-f4ad62763617)
![Captura3](https://github.com/signetlabdei/quic-ns-3/assets/119290035/3f01e58c-0a89-4a0e-9a75-3bc4c6c35341)

Thank you in advance

Regards,
Miguel

**Comment by fedech** [comment]
Hi Miguel,

This is a very good question: we implemented quic-variants-comparison as it is to provide a shared bottleneck, as the tcp-variants-comparison example from the Internet module does not have one (the gateway is shared, but flows have no actual links in common). We used quic-variants-comparison to generate Fig. 4 in the paper (the only one in which there are competing flows, as Fig. 2, 3 and 6 are for a single flow), and generating the same plot for TCP would require modifying the script in the same way.

I hope this answered your doubt!

Best,
Federico

**Comment by miguelsp99** [comment]
Hello Federico,

Thank you very much for your reply, it was very helpful!
Just one more question, I am currently trying to replicate the plots in Fig. 2, and I was wondering if you could then tell me what scripts you used for those plots, quic-variants-comparison or tcp-variants-comparison, or both? 
And also what files did you use to generate the Pacing Rate plot, because the quic-variants-comparison script generates me the CWND, RTT and RX files, and I'm trying to make it by splitting CWND/RTT but I don't get the same results.

Thank you in advance!!

Regards,
Miguel

**Comment by fedech** [comment]
You can enable tracing for the pacing rate by using the following code, as in the quic-pacing test:

  if (tracing)
    {
      AsciiTraceHelper ascii;
      pointToPoint.EnableAsciiAll (ascii.CreateFileStream ("quic-pacing.tr"));
      pointToPoint.EnablePcapAll ("quic-pacing", false);
    }

As for your other question, I'm honestly not sure, as this was 3 years ago and I don't have that version of the code any more. If I remember correctly, it was all done through quic-variants-comparison, but I may be wrong about this

Best,
Federico

**Comment by miguelsp99** [comment]
Hi Federico,

Okay, thank you very much for the explanation. It has been a great help!

Best,
Miguel.
:)
