### ISSUE TITLE
streams

### ISSUE THREAD

**Issue by tamerlvm** [signetlabdei/quic-ns-3#42]
hello , is there any option or attribute to change the number of streams while using quic protocol?
thanks in advance.

**Comment by fedech** [comment]
The quic-tester-streams example shows how to send a packet on a stream. There is no set number of stream, the stream to use is specified (if needed) in the method to send data through the socket as an optional parameter.

**Comment by abedaeed17** [comment]
Hi @fedech ,
I have two questions regarding this:
1. Can you please specify where in the ```quic-tester-streams``` example the socket number is specified? I could not figure out where it is mentioned in the example.
2. Is it possible to use multistreaming when using BulkSend app with quic?

I'd appreciate it a lot if you could help in these questions,
Thank you
