### ISSUE TITLE
Multistreaming using BulkSend

### ISSUE THREAD

**Issue by abedaeed17** [signetlabdei/quic-ns-3#45]
Hi,
I was wondering if it possible to use multiple streams within one QUIC connection using the BulkSend application. I could not find a relevant example about that.

If not, then I'd appreciate any help of how to set up more than one stream within one connection, and to continuously send unlimited data from the source to the destination over all stream concurrently.
It was noted in a closed issue (#42) that the ```quic-tester-streams``` shows how to send a packet on a stream, but I couldn't actually understand how it's done there, and is it possible to continuously send unlimited data (not just one packet)?
I don't have the permission to re-open that issue, so I'm opening this one.

Thanks! :)

**Comment by fedech** [comment]
This can be done through the Send method, but it isn't natively implemented in BulkSend. You can check out the Send method in QuicSocketBase, it specifies the stream number using the flags (ie, the second parameter in the function call.

We are not currently providing more help in implementing further features, as this issue tracker is meant for bugfixes, not as a help forum.
