### ISSUE TITLE
how to install quic model.

### ISSUE THREAD

**Issue by Fengww2014** [signetlabdei/quic-ns-3#5]
Finally, edit the wscript file of the internet module and add
        'model/ipv4-end-point.h',
        'model/ipv4-end-point-demux.h',
        'model/ipv6-end-point.h',
        'model/ipv6-end-point-demux.h',
to the headers.source list

when I do this, it goes wrong,  print out "source ns3 header file model/ipv6-end-point.h not found"
what can i do to solve the problem.

**Comment by mychele** [comment]
Hi,
if you are using the latest ns-3-dev there should not be the need to modify the script. Can you try?

**Comment by mangoWorkstation** [comment]
Hi, I've tried using ns3-dev for install quic module and tried to modify wscript file under quic folder, it seems like not working too.

Bugs report that "source ns3 header file model/ipv4-end-point.h not found."

what can i do to solve?

**Comment by mychele** [comment]
Hi, can you check that you are using the latest ns-3-dev? There should not be the need to modify the wscript.
