### ISSUE TITLE
Why the stream stop when i try quic-tester-stream.cc

### ISSUE THREAD

**Issue by liuyi12138** [signetlabdei/quic-ns-3#6]

**Comment by liuyi12138** [comment]
As i said, when i try to use quic-tester-stream.cc,it stop at 0.016s, and show MAX_DATA
i don't known how to sovle it
the trace:
+ 0.0161728 /NodeList/0/DeviceList/0/$ns3::PointToPointNetDevice/TxQueue/Enqueue ns3::PppHeader (Point-to-Point Protocol: IP (0x0021)) ns3::Ipv4Header (tos 0x0 DSCP Default ECN Not-ECT ttl 64 id 4 protocol 17 offset (bytes) 0 flags [none] length: 51 10.1.1.1 > 10.1.1.2) ns3::UdpHeader (length: 31 49153 > 9) ns3::QuicHeader (|0|1|0|1|0|1 Octet|
|ConnectionID 16215117342755731456|
|PacketNumber 5|
) ns3::QuicSubHeader (|MAX_DATA|
|Maximum Data 262144|
) ns3::QuicSubHeader (|ACK|
|Largest Acknowledged 4|
|Ack Delay 292|
|Ack Block Count 1|
|First Ack Block 4|
|Gap 2|
|Additional Ack Block 1|

**Comment by liuyi12138** [comment]
As i said, when i try to use quic-tester-stream.cc,it stop at 0.016s, and show MAX_DATA
i don't known how to sovle it
the trace:
+ 0.0161728 /NodeList/0/DeviceList/0/$ns3::PointToPointNetDevice/TxQueue/Enqueue ns3::PppHeader (Point-to-Point Protocol: IP (0x0021)) ns3::Ipv4Header (tos 0x0 DSCP Default ECN Not-ECT ttl 64 id 4 protocol 17 offset (bytes) 0 flags [none] length: 51 10.1.1.1 > 10.1.1.2) ns3::UdpHeader (length: 31 49153 > 9) ns3::QuicHeader (|0|1|0|1|0|1 Octet|
|ConnectionID 16215117342755731456|
|PacketNumber 5|
) ns3::QuicSubHeader (|MAX_DATA|
|Maximum Data 262144|
) ns3::QuicSubHeader (|ACK|
|Largest Acknowledged 4|
|Ack Delay 292|
|Ack Block Count 1|
|First Ack Block 4|
|Gap 2|
|Additional Ack Block 1|

**Comment by mychele** [comment]
Hi, 
are you using the unmodified example with the latest version of the code?

**Comment by liuyi12138** [comment]
no， i change the "Interval" to be larger,and it happened.
then i changed it back, and it works good,
I guess you didn't track ack in this project, which led to the situation i found.

**Comment by mychele** [comment]
Hi, to which interval are you referring to - and which value did you select?

**Comment by liuyi12138** [comment]
`dlClient.SetAttribute ("Interval", TimeValue (MicroSeconds(1000)));`
I choose the Interval time as 1s

**Comment by mychele** [comment]
Hi, the simulation works fine on my machine with 1s as interval. Are you using the latest version of the code?

**Comment by liuyi12138** [comment]
I do use the latest version of the code，and i will work ,
but Many packets will be MAX_DATA the throughPut will become low like this:
![throughPut](https://img-blog.csdnimg.cn/20200108212930482.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2h1c3RlaWM=,size_16,color_FFFFFF,t_70)

**Comment by liuyi12138** [comment]
the pictuce can't show ,it's url:
https://img-blog.csdnimg.cn/20200108212930482.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2h1c3RlaWM=,size_16,color_FFFFFF,t_70

**Comment by mychele** [comment]
Hi, if you send only one packet per second your throughput will be low. At the beginning you may have some overhead due to control packets..

**Comment by liuyi12138** [comment]
but why it send the MAX_DATA packets? Shouldn't it stop contracting

**Comment by fedech** [comment]
Solved in the new pull request, MAX_DATA packets are sent more rarely
