### ISSUE TITLE
Any idea to implement BBR statemachine?

### ISSUE THREAD

**Issue by PercyLau** [signetlabdei/quic-ns-3#7]
Hi, there!

Thank you for implementing the detailed module of quic in ns-3. Although in the current quic IETF draft-25 the default congestion control mechanism is mimicking TCP Reno, however,  BBR is more attractive because of its theoretical superior. I am willing to contribute to this part and there are some other works in TCP-BBR (https://github.com/mark-claypool/bbr). Could we have a discussion about the implementation here?

Sincerely,
Percy

**Comment by mychele** [comment]
Hi,
we are in the process of merging the code for BBR, everything should be up and running in the near future (see https://github.com/signetlabdei/quic/pull/3 and https://github.com/signetlabdei/quic/pull/5). We'll keep you posted!

**Comment by PercyLau** [comment]
Excellent work!
